#!/usr/bin/env bash
# Stage 2 - assemble a runnable Windows-ARM64 root from the built packages.
#
#   ./20-testroot.sh [/c/aarch64-root]
#
# Why a separate root is needed: an ARM64 process takes its idea of "/" from
# where msys-2.0.dll sits.  Run from the staging sysroot inside the x86_64
# installation, it resolves / to the *host* root, so the only /bin/sh it can
# find is x86_64 - and msys's fork emulation cannot clone an ARM64 parent's
# cygheap into an x86_64 child.  Anything that spawns a helper (git clone, a
# shell alias) dies with "child_copy: cygheap read copy failed".
#
# In a root whose usr/bin holds the ARM64 msys-2.0.dll, / is that directory,
# /bin maps to /usr/bin automatically, and everything works.

source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

ROOT="${1:-/c/aarch64-root}"

[[ -d ${SYSROOT}/usr/bin ]] || die "sysroot looks empty - run 10-packages.sh first"

msg "assembling ${ROOT}"
mkdir -p "${ROOT}"/{usr,etc,tmp,var,home}

# Refreshing an existing root fails without this.  Several packages install
# their files read-only (-r-xr-xr-x, and the Windows R attribute with them), and
# cp -a reproduces those modes, so the second run cannot overwrite what the
# first one wrote:
#
#     cp: cannot create regular file '.../usr/bin/bashbug': Permission denied
#
# The copy then stops partway, leaving a root that is half old and half new, and
# it never reaches the verification at the end - so nothing reports that the
# root is inconsistent.  Make everything writable before copying over it.
chmod -R u+w "${ROOT}" 2>/dev/null || true

# Everything the packages installed.
cp -a "${SYSROOT}/usr/." "${ROOT}/usr/"

# The runtime DLL lives in ${SYSROOT}/bin, not usr/bin, and the binaries need it
# beside them.  Copy only msys-2.0.dll: that directory also collects leftovers
# owned by no package - a stale msys-z.dll there once overwrote the packaged
# zlib in a test root and bsdtar quietly started reporting the older version.
cp -f "${SYSROOT}/bin/msys-2.0.dll" "${ROOT}/usr/bin/"

# The target's /etc, if the packages shipped one.
[[ -d ${SYSROOT}/etc ]] && cp -a "${SYSROOT}/etc/." "${ROOT}/etc/"

# A login profile, because three things in this root are configured for the
# staging sysroot rather than for a deployed root.  Each recipe passes
# --prefix=/usr/aarch64-pc-msys/usr, which is correct while building - it is
# where the files are staged - but that path is also compiled into the binaries,
# and inside this root "/" is the root itself, so it does not exist.
#
# Without these three the root looks broken in ways that read as build bugs:
#
#   tput: unknown terminal "xterm"
#   warning: templates not found in /usr/aarch64-pc-msys/usr/share/git-core/templates
#   fatal: unable to execute pager 'less'
#
# The first two are the staging-prefix problem and the data is present, just at
# the root-relative path.  The third is different: there is no pager in this
# root at all, because less is not one of the 23 chain packages.  It only shows
# up interactively - git skips the pager when stdout is not a tty, which is why
# scripted runs pass and a hand-run `git log` does not.
#
# The real fix for the first two is to build with --prefix=/usr and stage with
# DESTDIR, so nothing bakes in a build-time path.  Until then, this.
cat > "${ROOT}/etc/profile" <<'PROFILE'
# Generated by crossarm64/20-testroot.sh - edits here are overwritten.

# ncurses has --with-default-terminfo-dir=/usr/aarch64-pc-msys/usr/share/terminfo
# compiled in; the database is at /usr/share/terminfo in this root.
export TERMINFO_DIRS=/usr/share/terminfo
export TERMINFO=/usr/share/terminfo
: "${TERM:=xterm-256color}"
export TERM

# Same for git's templates, or git init/clone create repos with no hooks.
export GIT_TEMPLATE_DIR=/usr/share/git-core/templates

# No pager exists in this root - less is not part of the chain.
export GIT_PAGER=cat
export PAGER=cat

export PATH=/usr/bin:/usr/local/bin
export HOME=/home
export TMPDIR=/tmp

PS1='\[\e[1;32m\]aarch64\[\e[0m\]:\w\$ '

echo "Windows-ARM64 msys test root  -  bash ${BASH_VERSION}, ${MACHTYPE}"
PROFILE

cat > "${ROOT}/aarch64-shell.cmd" <<'CMD'
@echo off
rem Start a Windows-ARM64 msys shell in this root.
set "ROOT=%~dp0"
set "PATH=%ROOT%usr\bin;%PATH%"
"%ROOT%usr\bin\bash.exe" --login -i
CMD

msg "checking the result"
printf '  executables : %s\n' "$(ls "${ROOT}"/usr/bin/*.exe 2>/dev/null | wc -l)"
printf '  dlls        : %s\n' "$(ls "${ROOT}"/usr/bin/*.dll 2>/dev/null | wc -l)"
[[ -f ${ROOT}/usr/bin/msys-2.0.dll ]] || die "msys-2.0.dll missing from ${ROOT}/usr/bin"
[[ -f ${ROOT}/usr/bin/bash.exe ]]     || die "bash.exe missing from ${ROOT}/usr/bin"

# Anything in the root that differs from the sysroot means a stale file survived.
diffs=0
for f in "${SYSROOT}"/usr/bin/*.exe "${SYSROOT}"/usr/bin/*.dll; do
  b=$(basename "$f")
  cmp -s "$f" "${ROOT}/usr/bin/${b}" || { warn "differs from sysroot: ${b}"; diffs=$((diffs+1)); }
done
[[ $diffs -eq 0 ]] && msg "root matches the sysroot exactly"

msg "stage 2 complete - open a shell with ${ROOT}/aarch64-shell.cmd"
